# Generated by Django 4.0.6 on 2022-07-26 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_state_person_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='state',
        ),
    ]
