# Generated by Django 4.0.6 on 2022-07-26 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_remove_person_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='people.state'),
            preserve_default=False,
        ),
    ]
