# Generated by Django 4.1 on 2022-09-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='manyTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='many_types',
            field=models.ManyToManyField(blank=True, related_name='pokemon', to='pokeapp.manytypes'),
        ),
    ]
